"""Plan state persistence — survives bridge restart (U17).

Problem
-------
A ``/plan`` that's in flight when the bridge dies (cgroup OOM-kill,
SIGTERM during deploy, kernel panic, anything) loses its in-memory
``MultiPlanState``. The Feishu progress card the user sees becomes a
permanent "⏳ 思考中" ghost — the bridge no longer knows that plan
ever existed, so no error card is ever sent, no cancel signal reaches
any subprocess (they're dead anyway), and the user is left guessing
"is it still running? did it succeed silently? do I send it again?".

Scope of this module (deliberately narrow)
------------------------------------------
* **Persist a state snapshot** to ``DATA_DIR/_active_plans/<plan_id>.json``
  on every step status change + once at plan start. Only the fields the
  startup notifier needs are serialised — no ``threading.Event`` / ``Lock``,
  no ``cancel_ev``. The on-disk file is informational, not resumable.

* **Notify on restart**, NOT resume. ``resume_interrupted_plans`` is
  called once during bridge boot (in ``bridge.main`` alongside the
  existing ``resume_interrupted_crews``); it scans pending state files
  and pushes one card per affected chat:

      ⚠️ Plan 被中断 (bridge 重启) · MyPlan
      运行到第 3 / 5 步 ([dev] 实现 OAuth flow) 时中断。
      产出已保存在 .crew_workspace/。可重新发送同样需求复用
      或运行 /plan 全新开始。
      [按钮: 清除提示]

  The card button just removes the state file — no execution restart.
  Restarting execution would require rebuilding crew sub-task state
  that isn't checkpointed at step granularity, well beyond U17's value.

Why not in ``cmd_plan.py``
--------------------------
Keeps the persistence concern out of the hot path — ``_run_plan``'s
business logic stays focused on flow control, while this module owns
the on-disk schema and the "card on restart" UX. The two communicate
through three calls (``save_plan_state`` / ``delete_plan_state`` /
``mark_plan_phase``); the boundary is small enough that the persistence
behaviour can be swapped (e.g. to SQLite later) without touching
``cmd_plan``.

Fail-soft
---------
Every disk operation is wrapped — a plan run must never fail because
the persistence file couldn't be written. The startup notifier wraps
its whole scan loop so one corrupted state file can't prevent the
bridge from starting.
"""
from __future__ import annotations

import json
import os
import threading
import time
from pathlib import Path
from typing import TYPE_CHECKING

from larkhelm.log import _debug_log

if TYPE_CHECKING:
    # Import only for type hints to avoid a runtime circular import via
    # cmd_plan → plan_persistence → cmd_plan.
    from larkhelm.cmd_plan import MultiPlanState


# On-disk schema version. Bump when the JSON shape changes so the startup
# scanner can recognise + ignore (instead of crashing on) old files left
# over from a prior bridge build.
_STATE_SCHEMA_VERSION = 1

# Per-plan state file lives under ``DATA_DIR/_active_plans/<plan_id>.json``.
# Directory chosen for symmetry with the existing per-chat persistence
# folder ``DATA_DIR/_chat_state/`` — operators looking for "what state
# does the bridge keep on disk" find both in adjacent subdirs.
_DIRNAME = "_active_plans"

# Serialize on-disk writes per plan_id. Without this, two near-simultaneous
# ``save_plan_state`` calls (e.g. step transition + phase change) could
# write half a record each. ``threading.Lock`` is enough — the persistence
# path isn't async-contended; concurrent calls only happen within a single
# plan thread + occasional heartbeat-style writes.
_write_locks: "dict[str, threading.Lock]" = {}
_write_locks_meta = threading.Lock()


def _state_dir() -> Path:
    """Return ``DATA_DIR/_active_plans``, creating it if needed.

    Read ``_cfg.DATA_DIR`` lazily — this module imports early enough
    that ``_init_runtime`` may not have run yet at import time on some
    paths (e.g. test fixtures).
    """
    import larkhelm.config as _cfg
    p = Path(_cfg.DATA_DIR) / _DIRNAME
    p.mkdir(parents=True, exist_ok=True)
    return p


def _state_path(plan_id: str) -> Path:
    # ``plan_id`` is generated by ``uuid.uuid4().hex[:12]`` so it's already
    # safe for use as a filename — alphanum only. No sanitisation needed.
    return _state_dir() / f"{plan_id}.json"


def _get_write_lock(plan_id: str) -> threading.Lock:
    with _write_locks_meta:
        lk = _write_locks.get(plan_id)
        if lk is None:
            lk = threading.Lock()
            _write_locks[plan_id] = lk
        return lk


# ── Public API: lifecycle hooks called by ``cmd_plan._run_plan`` ─────────

def save_plan_state(state: "MultiPlanState") -> None:
    """Persist the current plan state to disk. Idempotent + fail-soft.

    Called once at plan start and again on every step status / phase
    transition so the on-disk record matches what the user is seeing.
    Cost is one short JSON serialize + atomic file write (``os.replace``
    after writing a temp file), measured at < 1 ms even on slow disks
    — fine to call frequently.
    """
    try:
        payload = _serialise(state)
        path = _state_path(state.plan_id)
        tmp = path.with_suffix(".json.tmp")
        with _get_write_lock(state.plan_id):
            tmp.write_text(json.dumps(payload, ensure_ascii=False),
                           encoding="utf-8")
            os.replace(tmp, path)
    except Exception as e:
        _debug_log(f"[PlanPersist] save_plan_state({state.plan_id[:8]}) failed: {e}")


def delete_plan_state(plan_id: str) -> None:
    """Remove the on-disk state for a finished / cancelled plan.

    Called from the ``finally`` block of ``_run_plan`` regardless of
    success / failure / cancel — once the plan thread has fully exited,
    its state is no longer "interrupted by bridge death". Idempotent.
    """
    try:
        _state_path(plan_id).unlink(missing_ok=True)
        with _write_locks_meta:
            _write_locks.pop(plan_id, None)
    except Exception as e:
        _debug_log(f"[PlanPersist] delete_plan_state({plan_id[:8]}) failed: {e}")


def list_pending_plan_states() -> list[dict]:
    """Return all on-disk plan state records (the "interrupted" set).

    Reading is read-only — no side effects, safe to call multiple times.
    Each entry is the dict shape produced by ``_serialise`` (see schema
    doc on that function). Corrupted / wrong-schema files are silently
    skipped so the startup notifier never crashes on bad data.
    """
    try:
        d = _state_dir()
    except Exception as e:
        _debug_log(f"[PlanPersist] list state dir failed: {e}")
        return []
    out: list[dict] = []
    for f in d.glob("*.json"):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
            if not isinstance(data, dict):
                continue
            if data.get("schema_version") != _STATE_SCHEMA_VERSION:
                _debug_log(f"[PlanPersist] skipping {f.name}: schema mismatch")
                continue
            out.append(data)
        except Exception as e:
            _debug_log(f"[PlanPersist] skipping unreadable {f.name}: {e}")
    return out


# ── Internals — serialisation ────────────────────────────────────────────

def _serialise(state: "MultiPlanState") -> dict:
    """Snapshot the bits of ``MultiPlanState`` the startup notifier needs.

    Skips non-pickleable members (``threading.Event`` / ``Lock``) and
    state-bag fields that have no meaning across a bridge restart
    (``_confirm_ev`` / ``_confirm_result``). The kept set is intentionally
    minimal — large state files just slow the startup scan, and the
    notifier only needs:

      * which plan + which chat (so the card goes to the right place)
      * how far it got (which step number / what its desc was)
      * what the current phase is when it died (so we can say "running"
        vs "waiting for confirm" vs "failed mid-step")

    Schema (locked at version 1):

      {
        "schema_version":  1,
        "plan_id":         "abc123def456",
        "chat_id":         "oc_xxxx",
        "title":           "<plan title>",
        "phase":           "running" | "waiting" | "done" | ...,
        "current_idx":     <int>,
        "start_time":      <epoch float>,
        "saved_at":        <epoch float>,
        "steps":           [{idx, type, desc, status, error, retry_count}],
      }
    """
    return {
        "schema_version": _STATE_SCHEMA_VERSION,
        "plan_id":        state.plan_id,
        "chat_id":        state.chat_id,
        "title":          state.title,
        "phase":          state.phase,
        "current_idx":    state.current_idx,
        "start_time":     state.start_time,
        "saved_at":       time.time(),
        "steps": [
            {
                "idx":         s.idx,
                "type":        s.type,
                "desc":        s.desc,
                "status":      s.status,
                "error":       (s.error or "")[:200],
                "retry_count": s.retry_count,
            }
            for s in state.steps
        ],
    }


# ── Bridge-startup notifier ──────────────────────────────────────────────

def resume_interrupted_plans() -> int:
    """Called from ``bridge.main`` on startup. Sends one notification card
    per interrupted plan + does NOT auto-resume execution.

    Returns the count of cards sent (mostly useful for the startup log
    + tests). Each on-disk state file is left in place so the user's
    card-button "清除提示" callback can find + delete it; a periodic
    GC of orphaned files isn't necessary because the user is exactly
    the right person to triage them.

    Wraps the whole scan loop in a broad except so one bad file (or
    a Feishu API outage during the scan) never blocks bridge startup.
    """
    try:
        records = list_pending_plan_states()
    except Exception as e:
        _debug_log(f"[PlanPersist] resume scan failed: {e}")
        return 0
    if not records:
        return 0

    sent = 0
    for rec in records:
        try:
            if _notify_chat_of_interrupted_plan(rec):
                sent += 1
        except Exception as e:
            _debug_log(
                f"[PlanPersist] notify failed for plan="
                f"{rec.get('plan_id', '?')[:8]}: {e}"
            )
    if sent:
        _debug_log(f"[PlanPersist] notified {sent} interrupted plan(s) on startup")
    return sent


def _notify_chat_of_interrupted_plan(rec: dict) -> bool:
    """Build + send the "Plan 被中断" card for a single interrupted plan.

    Returns True iff a card was actually sent. ``False`` is used to
    distinguish "skipped because the record was malformed (missing
    chat_id / plan_id)" from "tried to send and Feishu raised", which
    the caller wraps in its own try/except.
    """
    from larkhelm.lark_client import send_card

    chat_id = rec.get("chat_id", "")
    plan_id = rec.get("plan_id", "")
    title   = rec.get("title", "(无标题)")
    if not chat_id or not plan_id:
        return False

    steps = rec.get("steps", []) or []
    cur_idx = int(rec.get("current_idx", 0))
    total = len(steps)
    phase = rec.get("phase", "running")

    # Locate the step that was running when the bridge died — use
    # ``current_idx`` first, fall back to the first non-done step. This
    # mirrors how the progress card itself shows the "active step".
    active_step = None
    if 0 <= cur_idx < total:
        active_step = steps[cur_idx]
    else:
        for s in steps:
            if s.get("status") not in ("done", "skipped"):
                active_step = s
                break

    if active_step is not None:
        step_line = (
            f"运行到第 {active_step.get('idx', cur_idx) + 1} / {total} 步 "
            f"(**[{active_step.get('type', '?')}]** "
            f"{(active_step.get('desc') or '').strip()[:80]}) 时中断。"
        )
    else:
        step_line = f"共 {total} 个阶段，中断时阶段未知。"

    age_min = max(0, int((time.time() - float(rec.get("saved_at", 0))) / 60))
    age_str = f"{age_min} 分钟前" if age_min < 60 else f"{age_min // 60} 小时前"

    body = (
        f"**{title}**\n\n"
        f"{step_line}\n"
        f"上次心跳: {age_str} (phase=`{phase}`)\n\n"
        "**产出**: 已保存在 `.crew_workspace/`（design.md / tasks.json / "
        "changes.md / review.md 视进度而定）。可重发同样需求复用，或运行 "
        "`/plan` 全新开始。"
    )
    buttons = [("🗑️ 清除提示", f"plan_persist_clear:{plan_id}")]
    send_card(chat_id, f"⚠️ Plan 被中断 (bridge 重启)", body,
              color="orange", buttons=buttons)
    return True


def clear_plan_state_button(plan_id: str) -> bool:
    """Card-button callback: user pressed "🗑️ 清除提示" on the
    interrupted-plan notification. Just deletes the on-disk state.
    Returns True iff a file actually existed (for the button confirmation
    text). Safe to call multiple times.
    """
    path = _state_path(plan_id)
    existed = path.exists()
    delete_plan_state(plan_id)
    return existed
